### ISSUE TITLE
Can't run in Xcode 6.3 with swift 1.2

### ISSUE THREAD

**Issue by lmcmz** [MakeSchool/FlappyFly-Swift#1]
![2015-04-11 12 33 14](https://cloud.githubusercontent.com/assets/9669733/7102445/fa17bc56-e046-11e4-9e2c-f0edb70703c1.png)
Sorry to bother you. I'm a beginner in Cocos2d.
The tutorials you guys made are awesome.
But can you upload the code so I can run it in newest Xcode.
Thank you sincerely.
:)

**Comment by dionlarson** [comment]
Fixed the repo version to work with the newest version of Xcode and Swift 1.2. Be sure to open up the project in SpriteBuilder and publish before building in Xcode!

https://github.com/MakeSchool/FlappyFly-Swift/commit/f64c03943ff2f110fc437e6ba0c17b9426d88031

**Comment by dionlarson** [comment]
Actually might still be broken in Swift 1.2 -- taking another look.

**Comment by dionlarson** [comment]
Alright, fixed now. PNG compression seems to be broken in SpriteBuilder 1.4.7 so I turned it off.

https://github.com/MakeSchool/FlappyFly-Swift/commit/4887683f530a6028b4c59885188757a680cf2ad1
